[package]
name = "u7data"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
byteorder = "1"
image = "0.25"
three-d = "0.18"
three-d-asset = { version = "0.9.2", features = ["obj", "png"] }
